/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
  import syntaxtree.*;

  public class MiniJavaParser implements MiniJavaParserConstants {

/**
 * The MiniJava Grammar with AST construction
 */
  static final public 
Program Goal() throws ParseException {MainClass m; ClassDeclList cl = new ClassDeclList(); ClassDecl cd;
    m = MainClass();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CLASS:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      cd = TypeDeclaration();
cl.addElement(cd);
    }
    jj_consume_token(0);
{if ("" != null) return new Program(m, cl);}
    throw new Error("Missing return statement in function");
}

  static final public MainClass MainClass() throws ParseException {Identifier i1; Identifier i2; Statement s;
    jj_consume_token(CLASS);
    i1 = Identifier();
    jj_consume_token(LBRACE);
    jj_consume_token(PUBLIC);
    jj_consume_token(STATIC);
    jj_consume_token(VOID);
    jj_consume_token(MAIN);
    jj_consume_token(LPAREN);
    jj_consume_token(STRING);
    jj_consume_token(LBRACK);
    jj_consume_token(RBRACK);
    i2 = Identifier();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    label_2:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_2;
      }
      VarDeclaration();
    }
    s = Statement();
    jj_consume_token(RBRACE);
    jj_consume_token(RBRACE);
{if ("" != null) return new MainClass(i1, i2, s);}
    throw new Error("Missing return statement in function");
}

  static final public ClassDecl TypeDeclaration() throws ParseException {ClassDecl c;
    if (jj_2_2(3)) {
      c = ClassDeclaration();
{if ("" != null) return c;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CLASS:{
        c = ClassExtendsDeclaration();
{if ("" != null) return c;}
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public ClassDecl ClassDeclaration() throws ParseException {Identifier i; VarDecl v; VarDeclList vl = new VarDeclList(); MethodDecl md; MethodDeclList ml = new MethodDeclList();
    jj_consume_token(CLASS);
    i = Identifier();
    jj_consume_token(LBRACE);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case BOOLEAN:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      v = VarDeclaration();
vl.addElement(v);
    }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_4;
      }
      md = MethodDeclaration();
ml.addElement(md);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new ClassDeclSimple(i, vl, ml);}
    throw new Error("Missing return statement in function");
}

  static final public ClassDecl ClassExtendsDeclaration() throws ParseException {Identifier i; Identifier j; VarDecl v; VarDeclList vl = new VarDeclList(); MethodDecl md; MethodDeclList ml = new MethodDeclList();
    jj_consume_token(CLASS);
    i = Identifier();
    jj_consume_token(EXTENDS);
    j = Identifier();
    jj_consume_token(LBRACE);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case BOOLEAN:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_5;
      }
      v = VarDeclaration();
vl.addElement(v);
    }
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_6;
      }
      md = MethodDeclaration();
ml.addElement(md);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new ClassDeclExtends(i, j, vl, ml);}
    throw new Error("Missing return statement in function");
}

  static final public VarDecl VarDeclaration() throws ParseException {Type t; Identifier i;
    t = Type();
    i = Identifier();
    jj_consume_token(SEMI);
{if ("" != null) return new VarDecl(t, i);}
    throw new Error("Missing return statement in function");
}

  static final public MethodDecl MethodDeclaration() throws ParseException {Type t; Identifier i; FormalList fl = new FormalList(); Formal f; VarDecl v; VarDeclList vl = new VarDeclList(); Statement s; StatementList sl = new StatementList(); Exp e;
    jj_consume_token(PUBLIC);
    t = Type();
    i = Identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case BOOLEAN:
    case IDENTIFIER:{
      f = FormalParameter();
fl.addElement(f);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_7;
        }
        FormalParameterRest(fl);
      }
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    label_8:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_8;
      }
      v = VarDeclaration();
vl.addElement(v);
    }
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case PRINTLN:
      case IDENTIFIER:
      case LBRACE:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_9;
      }
      s = Statement();
sl.addElement(s);
    }
    jj_consume_token(RETURN);
    e = Expression();
    jj_consume_token(SEMI);
    jj_consume_token(RBRACE);
{if ("" != null) return new MethodDecl(t, i, fl, vl, sl, e);}
    throw new Error("Missing return statement in function");
}

  static final public Formal FormalParameter() throws ParseException {Type t; Identifier i;
    t = Type();
    i = Identifier();
{if ("" != null) return new Formal(t, i);}
    throw new Error("Missing return statement in function");
}

  static final public void FormalParameterRest(FormalList fl) throws ParseException {Formal f;
    jj_consume_token(COMMA);
    f = FormalParameter();
fl.addElement(f);
}

  static final public Type Type() throws ParseException {Type t; Token id;
    if (jj_2_4(3)) {
      t = ArrayType();
{if ("" != null) return t;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BOOLEAN:{
        t = BooleanType();
{if ("" != null) return t;}
        break;
        }
      case INT:{
        t = IntegerType();
{if ("" != null) return t;}
        break;
        }
      case IDENTIFIER:{
        id = jj_consume_token(IDENTIFIER);
{if ("" != null) return new IdentifierType(id.image);}
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Type ArrayType() throws ParseException {
    jj_consume_token(INT);
    jj_consume_token(LBRACK);
    jj_consume_token(RBRACK);
{if ("" != null) return new IntArrayType();}
    throw new Error("Missing return statement in function");
}

  static final public Type BooleanType() throws ParseException {
    jj_consume_token(BOOLEAN);
{if ("" != null) return new BooleanType();}
    throw new Error("Missing return statement in function");
}

  static final public Type IntegerType() throws ParseException {
    jj_consume_token(INT);
{if ("" != null) return new IntegerType();}
    throw new Error("Missing return statement in function");
}

  static final public Statement Statement() throws ParseException {Statement s;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACE:{
      s = Block();
{if ("" != null) return s;}
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      if (jj_2_5(2)) {
        s = AssignmentStatement();
{if ("" != null) return s;}
      } else if (jj_2_6(2)) {
        s = ArrayAssignmentStatement();
{if ("" != null) return s;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IF:{
          s = IfStatement();
{if ("" != null) return s;}
          break;
          }
        case WHILE:{
          s = WhileStatement();
{if ("" != null) return s;}
          break;
          }
        case PRINTLN:{
          s = PrintStatement();
{if ("" != null) return s;}
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Statement Block() throws ParseException {Statement s; StatementList sl = new StatementList();
    jj_consume_token(LBRACE);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case PRINTLN:
      case IDENTIFIER:
      case LBRACE:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_10;
      }
      s = Statement();
sl.addElement(s);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new Block(sl);}
    throw new Error("Missing return statement in function");
}

  static final public Statement AssignmentStatement() throws ParseException {Identifier i; Exp e;
    i = Identifier();
    jj_consume_token(ASSIGN);
    e = Expression();
    jj_consume_token(SEMI);
{if ("" != null) return new Assign(i, e);}
    throw new Error("Missing return statement in function");
}

  static final public Statement ArrayAssignmentStatement() throws ParseException {Identifier i; Exp e1; Exp e2;
    i = Identifier();
    jj_consume_token(LBRACK);
    e1 = Expression();
    jj_consume_token(RBRACK);
    jj_consume_token(ASSIGN);
    e2 = Expression();
    jj_consume_token(SEMI);
{if ("" != null) return new ArrayAssign(i, e1, e2);}
    throw new Error("Missing return statement in function");
}

  static final public Statement IfStatement() throws ParseException {Exp e; Statement s1; Statement s2;
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    e = Expression();
    jj_consume_token(RPAREN);
    s1 = Statement();
    jj_consume_token(ELSE);
    s2 = Statement();
{if ("" != null) return new If(e, s1, s2);}
    throw new Error("Missing return statement in function");
}

  static final public Statement WhileStatement() throws ParseException {Exp e; Statement s;
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    e = Expression();
    jj_consume_token(RPAREN);
    s = Statement();
{if ("" != null) return new While(e, s);}
    throw new Error("Missing return statement in function");
}

  static final public Statement PrintStatement() throws ParseException {Exp e;
    jj_consume_token(PRINTLN);
    jj_consume_token(LPAREN);
    e = Expression();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMI);
{if ("" != null) return new Print(e);}
    throw new Error("Missing return statement in function");
}

  static final public Exp Expression() throws ParseException {Exp e;
    if (jj_2_7(2147483647)) {
      e = AndExpression();
{if ("" != null) return e;}
    } else if (jj_2_8(2147483647)) {
      e = CompareExpression();
{if ("" != null) return e;}
    } else if (jj_2_9(2147483647)) {
      e = PlusExpression();
{if ("" != null) return e;}
    } else if (jj_2_10(2147483647)) {
      e = MinusExpression();
{if ("" != null) return e;}
    } else if (jj_2_11(2147483647)) {
      e = TimesExpression();
{if ("" != null) return e;}
    } else if (jj_2_12(2147483647)) {
      e = ArrayLookup();
{if ("" != null) return e;}
    } else if (jj_2_13(2147483647)) {
      e = ArrayLength();
{if ("" != null) return e;}
    } else if (jj_2_14(2147483647)) {
      e = MessageSend();
{if ("" != null) return e;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TRUE:
      case FALSE:
      case THIS:
      case NEW:
      case IDENTIFIER:
      case INTEGER_LITERAL:
      case LPAREN:
      case BANG:{
        e = PrimaryExpression();
{if ("" != null) return e;}
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Exp AndExpression() throws ParseException {Exp e1; Exp e2;
    e1 = PrimaryExpression();
    jj_consume_token(ANDAND);
    e2 = PrimaryExpression();
{if ("" != null) return new And(e1, e2);}
    throw new Error("Missing return statement in function");
}

  static final public Exp CompareExpression() throws ParseException {Exp e1; Exp e2;
    e1 = PrimaryExpression();
    jj_consume_token(LT);
    e2 = PrimaryExpression();
{if ("" != null) return new LessThan(e1, e2);}
    throw new Error("Missing return statement in function");
}

  static final public Exp PlusExpression() throws ParseException {Exp e1; Exp e2;
    e1 = PrimaryExpression();
    jj_consume_token(PLUS);
    e2 = PrimaryExpression();
{if ("" != null) return new Plus(e1, e2);}
    throw new Error("Missing return statement in function");
}

  static final public Exp MinusExpression() throws ParseException {Exp e1; Exp e2;
    e1 = PrimaryExpression();
    jj_consume_token(MINUS);
    e2 = PrimaryExpression();
{if ("" != null) return new Minus(e1, e2);}
    throw new Error("Missing return statement in function");
}

  static final public Exp TimesExpression() throws ParseException {Exp e1; Exp e2;
    e1 = PrimaryExpression();
    jj_consume_token(STAR);
    e2 = PrimaryExpression();
{if ("" != null) return new Times(e1, e2);}
    throw new Error("Missing return statement in function");
}

  static final public Exp ArrayLookup() throws ParseException {Exp e1; Exp e2;
    e1 = PrimaryExpression();
    jj_consume_token(LBRACK);
    e2 = PrimaryExpression();
    jj_consume_token(RBRACK);
{if ("" != null) return new ArrayLookup(e1, e2);}
    throw new Error("Missing return statement in function");
}

  static final public Exp ArrayLength() throws ParseException {Exp e;
    e = PrimaryExpression();
    jj_consume_token(DOT);
    jj_consume_token(LENGTH);
{if ("" != null) return new ArrayLength(e);}
    throw new Error("Missing return statement in function");
}

  static final public Exp MessageSend() throws ParseException {Exp e; Identifier id; ExpList el = new ExpList();
    e = PrimaryExpression();
    jj_consume_token(DOT);
    id = Identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case THIS:
    case NEW:
    case IDENTIFIER:
    case INTEGER_LITERAL:
    case LPAREN:
    case BANG:{
      el = ExpressionList();
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
{if ("" != null) return new Call(e, id, el);}
    throw new Error("Missing return statement in function");
}

  static final public ExpList ExpressionList() throws ParseException {ExpList el = new ExpList(); Exp e;
    e = Expression();
el.addElement(e);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_11;
      }
      ExpressionRest(el);
    }
{if ("" != null) return el;}
    throw new Error("Missing return statement in function");
}

  static final public void ExpressionRest(ExpList el) throws ParseException {Exp e;
    jj_consume_token(COMMA);
    e = Expression();
el.addElement(e);
}

  static final public Exp PrimaryExpression() throws ParseException {Token t; Exp e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      e = IntegerLiteral();
{if ("" != null) return e;}
      break;
      }
    case TRUE:{
      e = TrueLiteral();
{if ("" != null) return e;}
      break;
      }
    case FALSE:{
      e = FalseLiteral();
{if ("" != null) return e;}
      break;
      }
    case IDENTIFIER:{
      t = jj_consume_token(IDENTIFIER);
{if ("" != null) return new IdentifierExp(t.image);}
      break;
      }
    case THIS:{
      e = ThisExpression();
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      if (jj_2_15(3)) {
        e = ArrayAllocationExpression();
{if ("" != null) return e;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:{
          e = AllocationExpression();
{if ("" != null) return e;}
          break;
          }
        case BANG:{
          e = NotExpression();
{if ("" != null) return e;}
          break;
          }
        case LPAREN:{
          e = BracketExpression();
{if ("" != null) return e;}
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Exp IntegerLiteral() throws ParseException {Token t;
    t = jj_consume_token(INTEGER_LITERAL);
{if ("" != null) return new IntegerLiteral(Integer.parseInt(t.image));}
    throw new Error("Missing return statement in function");
}

  static final public Exp TrueLiteral() throws ParseException {
    jj_consume_token(TRUE);
{if ("" != null) return new True();}
    throw new Error("Missing return statement in function");
}

  static final public Exp FalseLiteral() throws ParseException {
    jj_consume_token(FALSE);
{if ("" != null) return new False();}
    throw new Error("Missing return statement in function");
}

  static final public Identifier Identifier() throws ParseException {Token t;
    t = jj_consume_token(IDENTIFIER);
{if ("" != null) return new Identifier(t.image);}
    throw new Error("Missing return statement in function");
}

  static final public Exp ThisExpression() throws ParseException {
    jj_consume_token(THIS);
{if ("" != null) return new This();}
    throw new Error("Missing return statement in function");
}

  static final public Exp ArrayAllocationExpression() throws ParseException {Exp e;
    jj_consume_token(NEW);
    jj_consume_token(INT);
    jj_consume_token(LBRACK);
    e = Expression();
    jj_consume_token(RBRACK);
{if ("" != null) return new NewArray(e);}
    throw new Error("Missing return statement in function");
}

  static final public Exp AllocationExpression() throws ParseException {Identifier id;
    jj_consume_token(NEW);
    id = Identifier();
    jj_consume_token(LPAREN);
    jj_consume_token(RPAREN);
{if ("" != null) return new NewObject(id);}
    throw new Error("Missing return statement in function");
}

  static final public Exp NotExpression() throws ParseException {Exp e;
    jj_consume_token(BANG);
    e = Expression();
{if ("" != null) return new Not(e);}
    throw new Error("Missing return statement in function");
}

  static final public Exp BracketExpression() throws ParseException {Exp e;
    jj_consume_token(LPAREN);
    e = Expression();
    jj_consume_token(RPAREN);
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_12()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_13()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_14()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_15()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_3R_ArrayAllocationExpression_375_3_18()
 {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(LBRACK)) return true;
    if (jj_3R_Expression_230_3_41()) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  static private boolean jj_3R_MinusExpression_278_3_54()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_VarDeclaration_116_3_12()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_ClassDeclaration_97_3_13()) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_ArrayAssignmentStatement_206_3_16()) return true;
    return false;
  }

  static private boolean jj_3R_ThisExpression_369_3_35()
 {
    if (jj_scan_token(THIS)) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_AssignmentStatement_200_3_15()) return true;
    return false;
  }

  static private boolean jj_3R_PlusExpression_272_3_53()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    return false;
  }

  static private boolean jj_3R_Identifier_363_3_20()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_CompareExpression_266_3_52()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(LT)) return true;
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    return false;
  }

  static private boolean jj_3R_IntegerType_170_3_40()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_FalseLiteral_357_3_34()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3_14()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_AndExpression_260_3_51()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(ANDAND)) return true;
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    return false;
  }

  static private boolean jj_3R_BooleanType_164_3_39()
 {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3_13()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  static private boolean jj_3R_TrueLiteral_351_3_33()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3_12()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(LBRACK)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_254_3_50()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    return false;
  }

  static private boolean jj_3R_ExpressionList_309_42_61()
 {
    if (jj_3R_ExpressionRest_315_3_62()) return true;
    return false;
  }

  static private boolean jj_3R_ArrayType_158_3_14()
 {
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(LBRACK)) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  static private boolean jj_3_11()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_251_3_49()
 {
    if (jj_3R_MessageSend_302_3_58()) return true;
    return false;
  }

  static private boolean jj_3_10()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  static private boolean jj_3R_IntegerLiteral_344_3_32()
 {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_248_3_48()
 {
    if (jj_3R_ArrayLength_296_3_57()) return true;
    return false;
  }

  static private boolean jj_3R_Type_152_3_31()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_245_3_47()
 {
    if (jj_3R_ArrayLookup_290_3_56()) return true;
    return false;
  }

  static private boolean jj_3R_Type_150_3_30()
 {
    if (jj_3R_IntegerType_170_3_40()) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(LT)) return true;
    return false;
  }

  static private boolean jj_3R_Type_148_3_29()
 {
    if (jj_3R_BooleanType_164_3_39()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_338_3_28()
 {
    if (jj_3R_BracketExpression_393_3_38()) return true;
    return false;
  }

  static private boolean jj_3R_Expression_242_3_46()
 {
    if (jj_3R_TimesExpression_284_3_55()) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(ANDAND)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_336_3_27()
 {
    if (jj_3R_NotExpression_387_3_37()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_ArrayType_158_3_14()) return true;
    return false;
  }

  static private boolean jj_3R_Type_145_3_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_148_3_29()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_150_3_30()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_152_3_31()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_Expression_239_3_45()
 {
    if (jj_3R_MinusExpression_278_3_54()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_334_3_26()
 {
    if (jj_3R_AllocationExpression_381_3_36()) return true;
    return false;
  }

  static private boolean jj_3R_Expression_236_3_44()
 {
    if (jj_3R_PlusExpression_272_3_53()) return true;
    return false;
  }

  static private boolean jj_3_15()
 {
    if (jj_3R_ArrayAllocationExpression_375_3_18()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_329_3_25()
 {
    if (jj_3R_ThisExpression_369_3_35()) return true;
    return false;
  }

  static private boolean jj_3R_Expression_233_3_43()
 {
    if (jj_3R_CompareExpression_266_3_52()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_327_3_24()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_230_3_42()
 {
    if (jj_3R_AndExpression_260_3_51()) return true;
    return false;
  }

  static private boolean jj_3R_Expression_230_3_41()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Expression_230_3_42()) {
    jj_scanpos = xsp;
    if (jj_3R_Expression_233_3_43()) {
    jj_scanpos = xsp;
    if (jj_3R_Expression_236_3_44()) {
    jj_scanpos = xsp;
    if (jj_3R_Expression_239_3_45()) {
    jj_scanpos = xsp;
    if (jj_3R_Expression_242_3_46()) {
    jj_scanpos = xsp;
    if (jj_3R_Expression_245_3_47()) {
    jj_scanpos = xsp;
    if (jj_3R_Expression_248_3_48()) {
    jj_scanpos = xsp;
    if (jj_3R_Expression_251_3_49()) {
    jj_scanpos = xsp;
    if (jj_3R_Expression_254_3_50()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_325_3_23()
 {
    if (jj_3R_FalseLiteral_357_3_34()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_323_3_22()
 {
    if (jj_3R_TrueLiteral_351_3_33()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_VarDeclaration_116_3_12()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_321_3_17()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryExpression_321_3_21()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_323_3_22()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_325_3_23()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_327_3_24()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_329_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_334_3_26()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_336_3_27()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_338_3_28()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_321_3_21()
 {
    if (jj_3R_IntegerLiteral_344_3_32()) return true;
    return false;
  }

  static private boolean jj_3R_ExpressionRest_315_3_62()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_Expression_230_3_41()) return true;
    return false;
  }

  static private boolean jj_3R_ExpressionList_309_3_60()
 {
    if (jj_3R_Expression_230_3_41()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ExpressionList_309_42_61()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_MessageSend_303_9_59()
 {
    if (jj_3R_ExpressionList_309_3_60()) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_116_3_12()
 {
    if (jj_3R_Type_145_3_19()) return true;
    if (jj_3R_Identifier_363_3_20()) return true;
    return false;
  }

  static private boolean jj_3R_MessageSend_302_3_58()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_Identifier_363_3_20()) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MessageSend_303_9_59()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_ArrayAssignmentStatement_206_3_16()
 {
    if (jj_3R_Identifier_363_3_20()) return true;
    if (jj_scan_token(LBRACK)) return true;
    return false;
  }

  static private boolean jj_3R_BracketExpression_393_3_38()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_Expression_230_3_41()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_ArrayLength_296_3_57()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  static private boolean jj_3R_AssignmentStatement_200_3_15()
 {
    if (jj_3R_Identifier_363_3_20()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  static private boolean jj_3R_NotExpression_387_3_37()
 {
    if (jj_scan_token(BANG)) return true;
    if (jj_3R_Expression_230_3_41()) return true;
    return false;
  }

  static private boolean jj_3R_ArrayLookup_290_3_56()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(LBRACK)) return true;
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  static private boolean jj_3R_ClassDeclaration_97_3_13()
 {
    if (jj_scan_token(CLASS)) return true;
    if (jj_3R_Identifier_363_3_20()) return true;
    if (jj_scan_token(LBRACE)) return true;
    return false;
  }

  static private boolean jj_3R_AllocationExpression_381_3_36()
 {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_Identifier_363_3_20()) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_TimesExpression_284_3_55()
 {
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    if (jj_scan_token(STAR)) return true;
    if (jj_3R_PrimaryExpression_321_3_17()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static JavaCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[18];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x100,0x100,0x20030000,0x200,0x20030000,0x200,0x0,0x20030000,0xa4140000,0x20030000,0x80000000,0x4140000,0xa4140000,0x61e00000,0x61e00000,0x0,0x60e00000,0x1000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x2002,0x2002,0x40,0x0,0x2002,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[15];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new JavaCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new JavaCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[46];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 18; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 46; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 15; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			   case 11: jj_3_12(); break;
			   case 12: jj_3_13(); break;
			   case 13: jj_3_14(); break;
			   case 14: jj_3_15(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                               }
